security:
    encoders:
        BlogBundle\Entity\User: plaintext

    providers:
        our_db_provider:
            entity:
                class: BlogBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: BlogBundle_admin_login
                check_path: BlogBundle_admin_login_check
                default_target_path: BlogBundle_admin
            pattern:    ^/
            provider: our_db_provider
            logout:
                path:   BlogBundle_admin_logout
                target: BlogBundle_admin_login

    access_control:
        - { path: BlogBundle_admin_login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: BlogBundle_admin_login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: BlogBundle_admin_logout, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }