<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll()
    {
		$query = $this->createQueryBuilder('post')
		    ->orderBy('post.id', 'DESC')
		    ->getQuery();
    	
    	return $query->getResult();
    }

    public function getOne($id)
    {
		$query = $this->createQueryBuilder('post')
			->where('post.id = :id')
			->setParameter('id', $id)
		    ->orderBy('post.id', 'DESC')
		    ->getQuery();
    	
    	return $query->getSingleResult();
    }
}
