<?php

namespace BlogBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll()
    {
		$query = $this->createQueryBuilder('tag')
		    ->orderBy('tag.id', 'DESC')
		    ->getQuery();
    	
    	return $query->getResult();
    }
}
